<a href="https://colab.research.google.com/github/Viktoriia-Osmanova/main-repo/blob/main/DS_module1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = [3, 5, 6, 4]
b = [2, 5, 7, 7]

In [ ]:
a = np.array(a)
b = np.array(b)

In [ ]:
a+b

array([ 5, 10, 13, 11])

##добуток


In [ ]:
a*b

array([ 6, 25, 42, 28])

##скалярний добуток

In [ ]:
np.dot(a,b)

101

##матриці

In [ ]:
matrix = np.array([[2,4,6,7,6],
                  [2,4,6,7,6],
                  [2,4,6,7,6],
                  [2,4,6,7,6]])

print(matrix)

[[2 4 6 7 6]
 [2 4 6 7 6]
 [2 4 6 7 6]
 [2 4 6 7 6]]


##множення 2х матриць - рядки першої матриці множаться на стовпчики 2ї