<a href="https://colab.research.google.com/github/Viktoriia-Osmanova/main-repo/blob/main/Python_DS_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [42]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
b = np.random.randint(1, 11, size=(5, 5), dtype=int)
print(b)

[[ 6  7  1  3  7]
 [ 9  2  8  6  5]
 [ 6  4  5  8  6]
 [ 2 10  2  7  4]
 [ 1  7  3  3  9]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
b = np.random.rand(4, 4)
print(b)

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1,11, size=(1,5))
b = np.random.randint(1,11, size=(1,5))
summa = a+b
vidnimanya=a-b
mnozhenya=a*b
print(a,b)
print(summa)
print(vidnimanya)
print(mnozhenya)


[[9 4 5 7 1]] [[4 9 4 1 6]]
[[13 13  9  8  7]]
[[ 5 -5  1  6 -5]]
[[36 36 20  7  6]]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)
print(a)
print(b)
c=np.dot(a,b)
print(c)

[10  6  5  1  4  9  8]
[ 4  3  3  8  7  4 10]
225


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 11, size = (2,2))
b = np.random.randint(1, 11, size = (2,3))
print(a)
print(b)
c = np.dot(a,b)
print(c)

[[6 6]
 [8 8]]
[[5 4 7]
 [3 7 4]]
[[48 66 66]
 [64 88 88]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [16]:
a=np.random.randint(1,11, size = (3,3))
print(a)
b = np.linalg.inv(a)
print(b)

[[9 8 3]
 [2 8 6]
 [4 2 8]]
[[ 0.11607143 -0.12946429  0.05357143]
 [ 0.01785714  0.13392857 -0.10714286]
 [-0.0625      0.03125     0.125     ]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [19]:
a = np.random.rand(4,4)
print(a)
transposed_matrix = np.transpose(a)

[[0.68410798 0.04086975 0.59102625 0.37507936]
 [0.28291127 0.74836787 0.02133876 0.36663026]
 [0.89872613 0.36703695 0.12042027 0.39412557]
 [0.11221628 0.71011662 0.91452067 0.31961487]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [24]:
a = np.random.randint(1,11, size=(3,4))
b = np.random.randint(1,11, size=(4))
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[6 1 6 4]
 [6 3 8 9]
 [4 8 7 3]]
[2 5 4 4]
[57 95 88]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [41]:
a = np.random.rand(2, 3)
b = np.random.rand(3)

print(a)
print(b)

c = np.dot(a, b)

print(c)


[[0.37673929 0.58906522 0.50032211]
 [0.91415184 0.70584977 0.22397851]]
[0.88625092 0.18399701 0.45814345]
[0.67149108 1.04265644]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [27]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
c = a*b
print(a)
print(b)
print(c)

[[3 1]
 [3 1]]
[[10  4]
 [ 1  4]]
[[30  4]
 [ 3  4]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [28]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[5 4]
 [3 1]]
[[3 1]
 [8 7]]
[[47 33]
 [17 10]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [34]:
a = np.random.randint(1,101, size=(5,5))
print(a)
c =np.sum(a)
print(c)

[[54 89 92 52 30]
 [87 13 39 78 57]
 [23 75 98 20 14]
 [81 17  3 45 89]
 [75 89  9 94 16]]
1339


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [35]:
a = np.random.randint(1,11, size=(4,4))
b = np.random.randint(1,11, size=(4,4))
print(a)
print(b)
c=a-b
print(c)

[[10  7  6  3]
 [ 6  9  9 10]
 [ 5 10  8  8]
 [10 10  1  6]]
[[2 9 6 5]
 [8 6 2 9]
 [8 4 7 5]
 [8 3 6 9]]
[[ 8 -2  0 -2]
 [-2  3  7  1]
 [-3  6  1  3]
 [ 2  7 -5 -3]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [36]:
a = np.random.rand(3,3)
print(a)
b = np.sum(a, axis=1, keepdims=True)

[[0.76435938 0.23904654 0.53365858]
 [0.77165935 0.83512874 0.17250824]
 [0.30618261 0.72168775 0.87898956]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [37]:
a = np.random.randint(1, 11, size=(3, 4))
print(a)
b = a ** 2
print(b)


[[ 1  4  6  6]
 [ 4  6 10 10]
 [ 5  9  9  7]]
[[  1  16  36  36]
 [ 16  36 100 100]
 [ 25  81  81  49]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [40]:
a = np.random.randint(1,51, size=4)
b = np.sqrt(a)
print(a)
print(b)

[25 39  1 40]
[5.         6.244998   1.         6.32455532]
